"""empty message

Revision ID: 139f9e53ce33
Revises: ba304da816dc
Create Date: 2025-05-31 00:53:54.796295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139f9e53ce33'
down_revision = 'ba304da816dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__person__favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__person__favorite')
    op.drop_table('favorites')
    # ### end Alembic commands ###
